import LocalizedStrings from 'react-native-localization';

export default language = new LocalizedStrings({
 en:{
    // Tabs
    news_tab_title: 'WoWs News',
    news_tab_label: 'News',
    search_tab_title: 'WoWs Info Ultimate',
    search_tab_label: 'Search',
    settings_tab_title: 'Settings',
    settings_tab_label: 'Settings',
    wiki_title: 'Wiki',
    more_title: 'More',
    open_in_browser_title: 'Open in browser',
    more_header: 'Websites & Tools',
    more_website_title: 'Website',
    more_tool_title: 'Tool',
    achievement_tab_title: 'Achievement',
    graph_tab_title: 'Graph',
    basic_tab_title: 'Basic',
    warship_tab_title: 'Warship',
    rank_tab_title: 'Rank',
    // Server
    server_russia: 'ru',
    server_europe: 'eu',
    server_north_america: 'com',
    server_asia: 'asia',
    server_na: 'na',
    // Day difference
    day_today: 'Today',
    day_yesterday: 'Yesterday',
    day_old: ' days old',
    // Wiki
    wiki_warship: 'Warship',
    wiki_achievement: 'Achievement',
    wiki_flag_camouflage: 'Flag - Camouflage',
    wiki_upgrade: 'Upgrade',
    wiki_map: 'Map',
    wiki_commander: 'Commander skill',
    wiki_collection: 'Collection',
    filter_done: 'Apply',
    filter_none: 'None',
    detail_status_title: 'Status',
    detail_survivability: 'Survivablity',
    survivability_health: 'Health',
    survivability_armour: 'Armour',
    survivability_protection: 'Protection',
    detail_artillery: 'Artillery',
    artillery_main: 'Main Battery',
    artillery_secondary: 'Secondary',
    detail_torpedoes: 'Torpedoes',
    detail_aa: 'AA Defense',
    detail_maneuverabilty: 'Maneuverabilty',
    detail_concealment: 'Concealment',
    concealment_ship: 'Ship',
    concealment_plane: 'Plane',
    detail_aircraft: 'Aircraft',
    aircraft_fighter: 'Fighter',
    aircraft_torpedo_bomber: 'Torpedo Bomber',
    aircraft_bomber: 'Dive Bomber',
    detail_upgrade_title: 'Upgrade',
    detail_next_ship_title: 'Next Ship(s)',
    // Drawer
    drawer_player_online: 'Player Online',
    drawer_wiki: 'WoWs Wiki',
    drawer_settings: 'Settings',
    drawer_about: 'About',
    // Search
    search_player: 'Player',
    search_clan: 'Clan',
    search_title: 'WoWs Search',
    // Player
    player_max_damage_dealt: 'Max damage dealt',
    player_max_xp: 'Max XP',
    player_max_kill: 'Max kill',
    player_max_plane: 'Max plane destroyed',
    player_max_main_battery: 'Main Battery',
    player_max_secondary: 'Secondary',
    player_max_torpedo: 'Torpedoes',
    player_max_ramming: 'Ramming',
    player_max_aircraft: 'Aircraft',
    player_respect: 'Please respect everyone\nDo not judge other player by statistics',
    player_survival_rate: 'Survival\nRate',
    player_average_frag: 'Average\nFrag',
    player_powered_by_number: 'Powered by WoWs Numbers',
    player_deleted_ship: 'DELETED SHIP',
    player_set_as_main: 'Set as Main',
    clan_member_count: 'Member',
    rank_season: 'Season ',
    // Personal Rating
    rating_bad: 'Improvement Needed',
    rating_below_average: 'Below Average',
    rating_average: 'Average',
    rating_good: 'Good',
    rating_very_good: 'Very Good',
    rating_great: 'Great',
    rating_unicum: 'Unicum',
    rating_super_unicum: 'Super Unicum',
    // Settings
    settings_theme_title: 'Theme',
    settings_theme: 'App theme',
    settings_language_title: 'Language',
    settings_news_language: 'News language',
    settings_api_language: 'API language',
    settings_iap_title: 'In-App Purchase',
    settings_remove_ads: 'Remove ads',
    settings_donation: 'Support development',
    settings_restore_purchase: 'Restore purchases',
    settings_about_title: 'About',
    settings_email_feedback: 'Email feedback',
    settings_write_review: 'Write a review',
    settings_source_code: 'Source code',
    settings_open_source_library: 'Open source libraries',
    settings_check_update: 'Check for update',
    settings_done: 'Done',
    settings_cancel: 'Cancel',
    // Website
    web_loading: 'Loading...',
    web_done_btn: 'Done',
    web_official_title: 'Official websites',
    web_official: 'World of Warships',
    web_premium_store: 'Premium store',
    web_official_wiki: 'Global Wiki',
    web_statistics_title: 'Statistics websites',
    web_number: 'WoWs Number',
    web_today: 'Warships Today',
    web_information_title: 'Supertest information',
    web_sea_group: 'Sea Group',
    web_daily_bounce: 'The Daily Bounce',
    web_facebook: 'Developer Blog',
    web_ranking_title: 'Ranking',
    web_ranking: 'Player Ranking [Suihei Koubou]',
    // Tool
    tool_wrinfo: '[Windows] WRInfo',
    tool_assist: '[Android] Community Assistant',
    // Extra
    no_information: 'No information',
    no_internet: 'No Internet connection',
    iap_failed: 'Your purchase could not be completed',
    iap_no_itunes: 'No response from AppStore',
    iap_success: 'Thank you for your purchase',
    why_opensource: 'WoWs Info is possible with all these wonderful libraries. This application is also open source because I want to be one of them who want to make this world better.',
 },
 zh: {
   // Tabs
   // Tabs
   news_tab_title: '最新消息',
   news_tab_label: '新闻',
   search_tab_title: 'WoWs Info究极版',
   search_tab_label: '搜索',
   settings_tab_title: '设置',
   settings_tab_label: '设置',
   wiki_title: '维基',
   more_title: '更多',
   open_in_browser_title: '在浏览器中打开',
   more_header: '网站和工具',
   more_website_title: '网站',
   more_tool_title: '工具',
   achievement_tab_title: '成就',
   graph_tab_title: '图表',
   basic_tab_title: '基本面',
   warship_tab_title: '战舰',
   rank_tab_title: '排位',
   // Server
   server_russia: 'ru',
   server_europe: 'eu',
   server_north_america: 'com',
   server_asia: 'asia',
   server_na: 'na',
   // Day difference
   day_today: '今天',
   day_yesterday: '昨天',
   day_old: '天前',
   // Wiki
   wiki_warship: '战舰',
   wiki_achievement: '成就',
   wiki_flag_camouflage: '旗子 - 迷彩',
   wiki_upgrade: '升级品',
   wiki_map: '地图',
   wiki_commander: '舰长技能',
   wiki_collection: '收藏品',
   filter_done: '确定',
   filter_none: '无',
   detail_status_title: '各项总值',
   detail_survivability: '生存力',
   survivability_health: '血量',
   survivability_armour: '装甲',
   survivability_protection: '鱼雷防护',
   detail_artillery: '火炮',
   artillery_main: '主炮',
   artillery_secondary: '副炮',
   detail_torpedoes: '鱼雷',
   detail_aa: '放空',
   detail_maneuverabilty: '机动性',
   detail_concealment: '隐蔽',
   concealment_ship: '被船发现',
   concealment_plane: '被飞机发现',
   detail_aircraft: '飞机',
   aircraft_fighter: '战斗机',
   aircraft_torpedo_bomber: '鱼雷机',
   aircraft_bomber: '核弹机',
   detail_upgrade_title: '升级品',
   detail_next_ship_title: '下一艘船',
   // Drawer
   drawer_player_online: '在线玩家',
   drawer_wiki: '战舰维基',
   drawer_settings: '设置',
   drawer_about: '关于APP',
   // Search
   search_player: '玩家',
   search_clan: '工会',
   search_title: '搜索',
   // Player
   player_max_damage_dealt: '最大伤害',
   player_max_xp: '最多经验',
   player_max_kill: '最多击杀',
   player_max_plane: '最多飞机击落',
   player_max_main_battery: '主炮',
   player_max_secondary: '副炮',
   player_max_torpedo: '鱼雷',
   player_max_ramming: '冲撞',
   player_max_aircraft: '飞机',
   player_respect: '请尊重每一位玩家 | 不要用数据评价其他玩家',
   player_survival_rate: '生存率',
   player_average_frag: '平均击杀',
   player_powered_by_number: '数据由WoWs Numbers提供',
   player_deleted_ship: '被删除的战舰',
   player_set_as_main: '设置为主账号',
   clan_member_count: '成员',
   rank_season: '赛季 ',
   // Personal Rating
   rating_bad: '还需提高',
   rating_below_average: '低于平均值',
   rating_average: '平均水平',
   rating_good: '好',
   rating_very_good: '很好',
   rating_great: '非常好',
   rating_unicum: '大佬水平',
   rating_super_unicum: '神佬水平',
   // Settings
   settings_theme_title: '主题',
   settings_theme: 'APP主题色',
   settings_language_title: '语言',
   settings_news_language: '最新消息语言',
   settings_api_language: 'API语言',
   settings_iap_title: '程序内购买',
   settings_remove_ads: '去除广告',
   settings_donation: '支持开发',
   settings_restore_purchase: '还原购买',
   settings_about_title: '关于APP',
   settings_email_feedback: '邮件反馈',
   settings_write_review: '给APP打分',
   settings_source_code: 'APP的源代码',
   settings_open_source_library: '开源项目',
   settings_check_update: '检查更新',
   settings_done: '完成',
   settings_cancel: '取消',
   // Website
   web_loading: '加载中...',
   web_done_btn: '完成',
   web_official_title: '官方网站',
   web_official: '战舰世界主站',
   web_premium_store: '商店',
   web_official_wiki: '官方维基',
   web_statistics_title: '数据网站',
   web_number: '战舰数字 WoWs Numbers',
   web_today: '今日战舰 Warship Today',
   web_information_title: '超测信息',
   web_sea_group: 'Sea Group',
   web_daily_bounce: 'The Daily Bounce',
   web_facebook: 'Facebook开发主页',
   web_ranking_title: '排名',
   web_ranking: '玩家排名 [Suihei Koubou]',
   // Tool
   tool_wrinfo: '[Windows] WRInfo',
   tool_assist: '[安卓] Community Assistant',
   // Extra
   no_information: '无数据',
   no_internet: '无网络连接',
   iap_failed: '无法完成您的购买',
   iap_no_itunes: '无法连接到AppStore',
   iap_success: '感谢您的购买',
   why_opensource: '没有这些开源项目就没有WoWs Info, 这个APP也是开源软件，因为我也想成为他们之一',   
 },
 ja: {
 }
});