import LocalizedStrings from 'react-native-localization';

export default language = new LocalizedStrings({
 en:{
    // Tabs
    news_tab_title: 'WoWs News',
    news_tab_label: 'News',
    search_tab_title: 'WoWs Info Ultimate',
    search_tab_label: 'Search',
    settings_tab_title: 'Settings',
    settings_tab_label: 'Settings',
    wiki_title: 'Wiki',
    more_title: 'More',
    open_in_browser_title: 'Open in browser',
    more_header: 'Websites & Tools',
    more_website_title: 'Website',
    more_tool_title: 'Tool',
    achievement_tab_title: 'Achievement',
    graph_tab_title: 'Graph',
    basic_tab_title: 'Basic',
    warship_tab_title: 'Warship',
    rank_tab_title: 'Rank',
    // Server
    server_russia: 'ru',
    server_europe: 'eu',
    server_north_america: 'com',
    server_asia: 'asia',
    server_na: 'na',
    // Day difference
    day_today: 'Today',
    day_yesterday: 'Yesterday',
    day_ago: ' days ago',
    // Wiki
    wiki_warship: 'Warship',
    wiki_achievement: 'Achievement',
    wiki_flag_camouflage: 'Flag - Camouflage',
    wiki_upgrade: 'Upgrade',
    wiki_map: 'Map',
    wiki_commander: 'Commander skill',
    wiki_collection: 'Collection',
    filter_done: 'Apply',
    filter_none: 'None',
    detail_status_title: 'Status',
    detail_survivability: 'Survivablity',
    survivability_health: 'Health',
    survivability_armour: 'Armour',
    survivability_protection: 'Protection',
    detail_artillery: 'Artillery',
    artillery_main: 'Main Battery',
    artillery_secondary: 'Secondary',
    detail_torpedoes: 'Torpedoes',
    detail_aa: 'AA Defense',
    detail_maneuverabilty: 'Maneuverabilty',
    detail_concealment: 'Concealment',
    concealment_ship: 'Ship',
    concealment_plane: 'Plane',
    detail_aircraft: 'Aircraft',
    aircraft_fighter: 'Fighter',
    aircraft_torpedo_bomber: 'Torpedo Bomber',
    aircraft_bomber: 'Dive Bomber',
    detail_upgrade_title: 'Upgrade',
    detail_next_ship_title: 'Next Ship(s)',
    // Drawer
    drawer_player_online: 'Player Online',
    drawer_wiki: 'WoWs Wiki',
    drawer_settings: 'Settings',
    drawer_about: 'About',
    // Search
    search_player: 'Player',
    search_clan: 'Clan',
    search_title: 'WoWs Search',
    search_main_account: 'Main: ',
    // Player
    player_max_damage_dealt: 'Max damage dealt',
    player_max_xp: 'Max XP',
    player_max_kill: 'Max kill',
    player_max_plane: 'Max plane destroyed',
    player_max_main_battery: 'Main Battery',
    player_max_secondary: 'Secondary',
    player_max_torpedo: 'Torpedoes',
    player_max_ramming: 'Ramming',
    player_max_aircraft: 'Aircraft',
    player_respect: 'Please respect everyone\nDo not judge other player by statistics',
    player_survival_rate: 'Survival\nRate',
    player_average_frag: 'Average\nFrag',
    player_powered_by_number: 'Powered by WoWs Numbers',
    player_deleted_ship: 'DELETED SHIP',
    player_set_as_main: 'Set as Main',
    // Personal Rating
    rating_bad: 'Improvement Needed',
    rating_below_average: 'Below Average',
    rating_average: 'Average',
    rating_good: 'Good',
    rating_very_good: 'Very Good',
    rating_great: 'Great',
    rating_unicum: 'Unicum',
    rating_super_unicum: 'Super Unicum',
    // Settings
    settings_theme: 'Change app theme',
    // Website
    web_done_btn: 'Done',
    web_official_title: 'Official websites',
    web_official: 'World of Warships',
    web_premium_store: 'Premium store',
    web_official_wiki: 'Global Wiki',
    web_statistics_title: 'Statistics websites',
    web_number: 'WoWs Number',
    web_today: 'Warships Today',
    web_information_title: 'Supertest information',
    web_sea_group: 'Sea Group',
    web_daily_bounce: 'The Daily Bounce',
    web_facebook: 'Developer Blog',
    web_ranking_title: 'Ranking',
    web_ranking: 'Player Ranking [Suihei Koubou]',
    // Tool
    tool_wrinfo: '[Windows] WRInfo',
    tool_assist: '[Android] Community Assistant',
    // Extra
    no_information: 'No information'
 },
 zh: {
   // Tabs
   news_tab_title: '最新消息',
   news_tab_label: '新闻',
   search_tab_title: 'WoWs Info 究极版',
   search_tab_label: '搜索',
   settings_tab_title: '设置',
   settings_tab_label: '设置',
 },
 ja: {
 }
});