import LocalizedStrings from 'react-native-localization';

export const lang = new LocalizedStrings({
  en: {
    /// Setup section
    setup_title: 'Setup WoWs Info',
    setup_done_button: 'Done',
    setup_loading: 'Loading...',
    /// Home section
    // Friend section
    friend_clan_title: 'Clan',
    friend_player_title: 'Player',
    // Update section
    update_version_title: 'Version',
    update_app_version: 'App ->',
    update_game_version: 'Game ->',
    // Button section
    button_settings_label: 'Settings',
    button_menu_label: 'Menu',
    button_back_label: 'Go Back',
    button_home_label: 'Home',
    /// Wiki section
    wiki_warship_footer: 'Filter',
    wiki_warship_filter_btn: 'Apply',
    wiki_warship_reset_btn: 'Reset',
    wiki_warship_filter_placeholder: 'Enter a ship name',
    wiki_warship_filter_tier: 'Tier',
    wiki_warship_filter_nation: 'Nation / Region',
    wiki_warship_filter_type: 'Type',
    wiki_warship_filter_premium: 'Premium ship',
    // Warship Detail
    warship_unkown: 'Unknown',
    warship_model: '3D Model',
    warship_update_module: 'Update ship modules',
    warship_default_module: 'Default',
    warship_apply_module: 'Apply',
    warship_survivability: 'Survivability',
    warship_survivability_health: 'Health',
    warship_survivability_armour: 'Armour',
    warship_survivability_protection: 'Protection',
    warship_artillery: 'Artillery',
    warship_artillery_main: 'Main Battery',
    warship_avg_damage: 'Average Damage',
    warship_avg_winrate: 'Average Winrate',
    warship_avg_frag: 'Average Frags',
    warship_weapon_reload: 'Reload Time',
    warship_weapon_range: 'Range',
    warship_weapon_configuration: 'Configuration',
    warship_weapon_dispersion: 'Max Dispersion',
    warship_weapon_rotation: 'Rotation Time',
    warship_weapon_fire_chance: 'Fire Chance',
    warship_artillery_main_weight: 'Weight',
    warship_weapon_damage: 'Max Damage',
    warship_weapon_potential_damage: 'Potential Damage',
    warship_weapon_ap_overmatch: 'Overmatch',
    warship_weapon_he_penetration: 'Penetration',
    warship_weapon_speed: 'Speed',
    warship_ramming: 'Ramming',
    warship_artillery_secondary: 'Secondary',
    warship_torpedoes: 'Torpedoes',
    warship_torpedoes_visible_distance: 'Detection',
    warship_antiaircraft: 'AA Defense',
    warship_maneuverabilty: 'Maneuverabilty',
    warship_maneuverabilty_turning: 'Turning Radius',
    warship_maneuverabilty_speed: 'Max Speed',
    warship_maneuverabilty_rudder_time: 'Rudder Time',
    warship_aircraft: 'Aircraft',
    warship_concealment: 'Concealment',
    warship_concealment_detect_by_ship: 'Detection by Ship',
    warship_concealment_detect_by_plane: 'Detection by Plane',
    warship_upgrades: 'Upgrades',
    warship_next_ship: 'Next ship(s)',
    warship_compare_similar: 'Compare similar ships',
    /// Menu section
    /// Settings section
    server_name: ['Russia', 'Europe', 'North America', 'Asia'],
    setting_game_server: 'Game Server',
    setting_api_language: 'API Language',
    setting_app_language: 'WoWs Info Language',
    settings_api_settings: 'API Settings',
    settings_app_settings: 'App Settings',
    settings_app_dark_mode: 'Dark mode',
    settings_app_theme_colour: 'Theme colour',
    settings_app_no_image_mode: 'No image mode',
    settings_app_swap_buttons: 'Swap bottom buttons',
    settings_app_send_feedback: 'Feedback',
    settings_app_send_feedback_subtitle: 'Send an email to developer',
    settings_app_report_issues: 'Report an issue',
    settings_app_write_review: 'Write a review',
    settings_app_share: 'Share with friends',
    settings_app_share_subtitle: 'Share WoWs Info if you enjoy using it!',
    settings_app_check_for_update: 'Check for update',
    settings_app_no_update: 'You are using the latest version.',
    settings_app_has_update: 'Update {0} is available',
    settings_open_source: 'Open Source',
    settings_open_source_github: 'Github',
    settings_open_source_licence: 'Licences',
    settings_open_source_licence_subtitle: 'Great modules that are used by WoWs Info',
    // Footer
    menu_footer: 'Search',
    menu_search_player: 'Player',
    menu_search_clan: 'Clan',
    // Search bar
    search_player_online: 'online',
    // Wiki
    wiki_section_title: 'Encyclopedia',
    wiki_achievement: 'Achievement',
    wiki_warships: 'Warships',
    wiki_upgrades: 'Upgrades',
    wiki_flags: 'Flags/Camouflages',
    wiki_skills: 'Commander Skills',
    wiki_skills_tier: 'Tier',
    wiki_skills_reset: 'Reset',
    wiki_skills_point: 'point(s)',
    wiki_maps: 'Maps',
    wiki_collections: 'Collections',
    // Extra
    extra_section_title: 'Extra',
    extra_support_wowsinfo: 'Support WoWs Info',
    extra_rs_beta: 'Realtime Statistics Beta',
    extra_rs_beta_download: 'Download RS on your computer',
    extra_support_wowsinfo_subtitle: 'Donations and Ads',
    support_paypal: 'PayPal',
    support_patreon: 'Patreon',
    support_wechat: 'WeChat',
    support_ads: 'Ads Settings',
    support_ads_banner: 'Show Ads',
    support_ads_fullscreen: 'Show Ads on launch',
    // Websites
    website_title: 'Websites',
    website_official_site: 'World of Warships',
    website_premium: 'Premium Shop',
    website_global_wiki: 'Global Wiki',
    website_dev_blog: 'Developer Blog',
    website_sea_group: 'SEA Group',
    website_daily_bounce: 'The Daily Bounce',
    website_numbers: 'WoWS Stats & Numbers',
    website_today: 'Warships.Today',
    website_ranking: 'Player Ranking',
    website_models: 'Warships Models',
    // YouTubers
    youtuber_title: 'YouTubers',
    youtuber_official: 'WoWs Official',
    youtuber_flambass: 'Flambass',
    youtuber_notser: 'Notser',
    youtuber_jingles: 'The Mighty Jingles',
    youtuber_panzerknacker: 'Panzerknacker',
    youtuber_flamu: 'Flamu',
    youtuber_yuro: 'Yuro',
    youtuber_iChaseGaming: 'iChaseGaming',
    youtuber_NoZoupForYou: 'NoZoupForYou',
    // Tools
    tool_title: 'Tools',
    /// Player section
    // Tabs
    tab_achievement_title: 'Achievement',
    tab_graph_title: 'Graph',
    tab_ship_title: 'Ship',
    tab_rank_title: 'Rank',
    // Rating
    rating_title: 'Personal Rating',
    rating_description: 'It is a measure of skill.',
    rating_read_more: '- Read More -',
    rating_warning: 'Please do not judge other players simply by his/her rating',
    rating_author: 'By Wiochi',
    rating_scale: 'Colour Scale',
    rating_bad: 'Improvement Needed',
    rating_below_average: 'Below Average',
    rating_average: 'Average',
    rating_good: 'Good',
    rating_very_good: 'Very Good',
    rating_great: 'Great',
    rating_unicum: 'Unicum',
    rating_super_unicum: 'SUPER Unicum',
    rating_Unkwown: 'Unknown',
    // Basic
    basic_data_unknown: 'Unknown',
    basic_level_tier: 'Level',
    basic_register_date: 'Register Date',
    basic_last_battle: 'Last Battle',
    basic_more_stat: '- Show More -',
    basic_add_friend: 'Add to list',
    basic_set_main: 'Set as Main Account',
    // Detailed
    detailed_win: 'Wins',
    detailed_draw: 'Draws',
    detailed_loss: 'Losses',
    detailed_survived: 'Survived Battles',
    detailed_total_xp: 'Total XP',
    detailed_survived_win: 'Survived Wins',
    detailed_survival_rate: 'Survival Rate',
    detailed_survivied_win_rate: 'Survived Win Rate',
    detailed_total_potential_damage: 'Total Potential Damage',
    detailed_avg_potential_damage: 'Avg Potential Damage',
    detailed_total_torp_potential_damage: 'Total Torp Potential Damage',
    detailed_avg_torp_potential_damage: 'Avg Torp Potential Damage',
    detailed_total_scouting_damage: 'Total Scouting Damage',
    detailed_avg_scouting_damage: 'Avg Scouting Damage',
    detailed_total_damage: 'Total Damage Dealt',
    detailed_damage_potential_ratio: 'Damage Dealt / Potential',
    detailed_total_spotted: 'Total Spotted',
    detailed_avg_spotted: 'Avg Spotted',
    detailed_total_frag: 'Total Frags',
    detailed_frag_spot_ratio: 'Frag / Spotted',
    detailed_total_plane_killed: 'Total Planed Destroyed',
    detailed_avg_plane_killed: 'Avg Planed Destroyed',
    // Ship detail
    ship_detail_damage: 'Damage',
    ship_detail_winrate: 'Winrate',
    ship_detail_frag: 'Frags',
    ship_sort_battle: 'Battle',
    ship_sort_colour: 'Colour',
    // Rank
    rank_season_title: 'Season',
    // Clan
    clan_created_date: 'Created At',
    clan_creator_name: 'Creator',
    clan_leader_name: 'Leader',
    clan_member_title: 'Member',
    // Record
    record_title: 'Records',
    record_best_ship: 'Best Ship',
    record_max_damage_dealt: 'Max Damage Dealt',
    record_max_frags_battle: 'Max Frags',
    record_max_planes_killed: 'Max Planes Destroyed',
    record_max_xp: 'Max XP',
    record_max_ships_spotted: 'Max Ships Spotted',
    record_max_total_agro: 'Max Potential Damage Dealt',
    record_max_damage_scouting: 'Max Scouting Damage',
    // Weapon record
    weapon_max_frags: 'Max Frags',
    weapon_total_frags: 'Total Frags',
    weapon_hit_ratio: 'Hit Ratio',
    /// App name section
    app_name: 'WoWs Info Origin+',
    wowsinfo_black: 'Black',
    wowsinfo_white: 'White',
    wowsinfo_ultra: 'Ultra',
    wowsinfo_ultimate: 'Ultimate',
    wowsinfo_pro: 'Pro',
    wowsinfo_new: 'New',
    wowsinfo_go: 'Go',
    wowsinfo_origin: 'Origin',
    wowsinfo_free: 'Free',
    /// RS section
    // Tips
    rs_tip_download: '1. Download',
    rs_tip_one: 'Please visit this Github repository and download the latest release. This program does not use lots of RAM and storage. Currently, it is in its beta stage and has no GUI.\n',
    rs_tip_setup: '2. Setup',
    rs_tip_two: "Copy and paste the path of your game folder into this program and you have to run it with admin or it will not work. It won't do anything harmful to your computer.\n",
    rs_tip_enjoy: '3. Enjoy',
    rs_tip_three: 'Enter the IP address you see on the screen and WoWs Info will start giving you real-time statistics for both teams.\n',
    /// Error section
    // General errors
    error_title: 'Error',
    error_download_issue: 'Failed to update data. \nPlease try again later.\n\nIf it persists, please try using a VPN or changing your DNS.\nIf it still persists, it means that the server is OFFLINE',
    /// About WoWs Info section
    // Github link
    abour_github_link: 'https://github.com/HenryQuan/WoWs-Info-Origin/blob/master/README.md',
    unlock_pro_features: 'Unlock Pro features',
  },
  zh: {
    /// Setup section
    setup_title: '设置WoWs Info',
    setup_done_button: '完成',
    setup_loading: '加载中...',
    /// Home section
    // Friend section
    friend_clan_title: '工会',
    friend_player_title: '玩家',
    // Update section
    update_version_title: '版本信息',
    update_app_version: 'APP版本 ->',
    update_game_version: '游戏版本 ->',
    // Button section
    button_settings_label: '设置',
    button_menu_label: '主菜单',
    button_back_label: '返回',
    button_home_label: '主页面',
    /// Wiki section
    wiki_warship_footer: '筛选',
    wiki_warship_filter_btn: '确定',
    wiki_warship_reset_btn: '还原',
    wiki_warship_filter_placeholder: '输入船名',
    wiki_warship_filter_tier: '等级',
    wiki_warship_filter_nation: '国家/区域',
    wiki_warship_filter_type: '类型',
    wiki_warship_filter_premium: '金币船',
    // Warship Detail
    warship_unkown: '未知',
    warship_model: '3D模型',
    warship_update_module: '更新组件',
    warship_default_module: '默认组件',
    warship_apply_module: '确定',
    warship_survivability: '生存力',
    warship_survivability_health: '血量',
    warship_survivability_armour: '装甲',
    warship_survivability_protection: '防护',
    warship_artillery: '火炮',
    warship_artillery_main: '主炮',
    warship_avg_damage: '平均伤害',
    warship_avg_winrate: '平均胜率',
    warship_avg_frag: '平均击杀',
    warship_weapon_reload: '装填时间',
    warship_weapon_range: '射程',
    warship_weapon_configuration: '配置',
    warship_weapon_dispersion: '最大散步',
    warship_weapon_rotation: '转动时间',
    warship_weapon_fire_chance: '点火率',
    warship_artillery_main_weight: '重量',
    warship_weapon_damage: '最大伤害',
    warship_weapon_potential_damage: '潜在伤害',
    warship_weapon_ap_overmatch: '碾压',
    warship_weapon_he_penetration: '穿深',
    warship_weapon_speed: '速度',
    warship_ramming: '冲撞',
    warship_artillery_secondary: '副炮',
    warship_torpedoes: '鱼雷',
    warship_torpedoes_visible_distance: '探测距离',
    warship_antiaircraft: '防空',
    warship_maneuverabilty: '机动性',
    warship_maneuverabilty_turning: '转舵半径',
    warship_maneuverabilty_speed: '最大航速',
    warship_maneuverabilty_rudder_time: '转舵时间',
    warship_aircraft: '飞机',
    warship_concealment: '隐蔽',
    warship_concealment_detect_by_ship: '被船发现距离',
    warship_concealment_detect_by_plane: '被飞机发现距离',
    warship_upgrades: '升级品',
    warship_next_ship: '可升级为',
    warship_compare_similar: '对比类似的战舰',
    /// Menu section
    /// Settings section
    server_name: ['俄服', '欧服', '美服', '亚服'],
    setting_game_server: '游戏服务器',
    setting_api_language: 'API语言',
    setting_app_language: 'WoWs Info语言',
    settings_api_settings: 'API接口设置',
    settings_app_settings: '软件设置',
    settings_app_dark_mode: '夜间模式',
    settings_app_theme_colour: '主题颜色',
    settings_app_no_image_mode: '无图模式',
    settings_app_swap_buttons: '交换下面的按钮',
    settings_app_send_feedback: '反馈',
    settings_app_send_feedback_subtitle: '给开发者发邮件',
    settings_app_report_issues: '报告错误',
    settings_app_write_review: '给软件打分',
    settings_app_share: '分享',
    settings_app_share_subtitle: '如果喜欢使用WoWs Info，记得分享给小伙伴们！',
    settings_app_check_for_update: '检查更新',
    settings_app_no_update: '已经是最新版本',
    settings_app_has_update: '下载 {0} 版本',
    settings_open_source: '开源相关',
    settings_open_source_github: 'Github',
    settings_open_source_licence: '三方许可',
    settings_open_source_licence_subtitle: 'WoWs Info使用了很多优秀的三方组件',
    // Footer
    menu_footer: '开始搜索',
    menu_search_player: '玩家',
    menu_search_clan: '工会',
    // Search bar
    search_player_online: '在线',
    // Wiki
    wiki_section_title: '战舰百科',
    wiki_achievement: '成就',
    wiki_warships: '战舰',
    wiki_upgrades: '升级品',
    wiki_flags: '旗子与迷彩',
    wiki_skills: '舰长技能',
    wiki_skills_tier: '等级',
    wiki_skills_reset: '还原',
    wiki_skills_point: '点',
    wiki_maps: '地图',
    wiki_collections: '收藏',
    // Extra
    extra_section_title: '其他',
    extra_support_wowsinfo: '支持WoWs Info',
    extra_rs_beta: '实时数据 Beta',
    extra_rs_beta_download: '在电脑上下载RS',
    extra_support_wowsinfo_subtitle: '捐助以及广告',
    support_paypal: '贝宝',
    support_patreon: 'Patreon',
    support_wechat: '微信',
    support_ads: '广告设置',
    support_ads_banner: '显示广告',
    support_ads_fullscreen: '启动APP时显示广告',
    // Websites
    website_title: '网站',
    website_official_site: '战舰世界官网',
    website_premium: '战舰商城',
    website_global_wiki: '战舰全球百科',
    website_dev_blog: '开发者的脸书',
    website_sea_group: 'SEA Group',
    website_daily_bounce: 'The Daily Bounce',
    website_numbers: '战舰数字',
    website_today: '今日战舰',
    website_ranking: '玩家排行榜',
    website_models: '战舰模型',
    // YouTubers
    youtuber_title: '油管主',
    youtuber_official: '战舰世界官方频道',
    youtuber_flambass: '舰长 Flambass',
    youtuber_notser: '舰长 Notser',
    youtuber_jingles: '舰长 The Mighty Jingles',
    youtuber_panzerknacker: '舰长 Panzerknacker',
    youtuber_flamu: '舰长 Flamu',
    youtuber_yuro: '舰长 Yuro',
    youtuber_iChaseGaming: '舰长 iChaseGaming',
    youtuber_NoZoupForYou: '舰长 NoZoupForYou',
    // Tools
    tool_title: '工具',
    /// Player section
    // Tabs
    tab_achievement_title: '成就',
    tab_graph_title: '图表',
    tab_ship_title: '战舰',
    tab_rank_title: '排位赛',
    // Rating
    rating_title: '个人评分',
    rating_description: '用来测量玩家的技能',
    rating_read_more: '- 阅读更多 -',
    rating_warning: '请不要只用数据来评价玩家',
    rating_author: '舰长 Wiochi',
    rating_scale: '评分表',
    rating_bad: '还需努力',
    rating_below_average: '低于平均',
    rating_average: '平均水平',
    rating_good: '好',
    rating_very_good: '很好',
    rating_great: '非常好',
    rating_unicum: '大佬平均',
    rating_super_unicum: '神佬平均',
    rating_Unkwown: '水平未知',
    // Basic
    basic_data_unknown: '未知',
    basic_level_tier: '等级',
    basic_register_date: '注册日期',
    basic_last_battle: '最后的战斗',
    basic_more_stat: '- 显示更多数据 -',
    basic_add_friend: '增加到列表',
    basic_set_main: '设为主账号',
    // Detailed
    detailed_win: '胜利',
    detailed_draw: '平局',
    detailed_loss: '失败',
    detailed_survived: '存活场数',
    detailed_total_xp: '总经验',
    detailed_survived_win: '存活胜利',
    detailed_survival_rate: '生存率',
    detailed_survivied_win_rate: '存活胜率',
    detailed_total_potential_damage: '总潜在伤害',
    detailed_avg_potential_damage: '平均潜在伤害',
    detailed_total_torp_potential_damage: '鱼雷潜在伤害',
    detailed_avg_torp_potential_damage: '平均鱼雷潜在伤害',
    detailed_total_scouting_damage: '总侦查伤害',
    detailed_avg_scouting_damage: '平均侦查伤害',
    detailed_total_damage: '总伤害',
    detailed_damage_potential_ratio: '真实伤害 / 潜在伤害',
    detailed_total_spotted: '总侦测数',
    detailed_avg_spotted: '平均侦测',
    detailed_total_frag: '总击杀',
    detailed_frag_spot_ratio: '击杀 / 侦测',
    detailed_total_plane_killed: '总飞机击落',
    detailed_avg_plane_killed: '平均飞机击落',
    // Ship detail
    ship_detail_damage: '伤害',
    ship_detail_winrate: '胜率',
    ship_detail_frag: '击杀',
    ship_sort_battle: '场数',
    ship_sort_colour: '颜色',
    // Rank
    rank_season_title: '赛季',
    // Clan
    clan_created_date: '创建于',
    clan_creator_name: '创建者',
    clan_leader_name: '指挥官',
    clan_member_title: '成员',
    // Record
    record_title: '记录',
    record_best_ship: '最好',
    record_max_damage_dealt: '最大伤害',
    record_max_frags_battle: '最多击杀',
    record_max_planes_killed: '最多飞机击落',
    record_max_xp: '最多经验',
    record_max_ships_spotted: '最多侦测',
    record_max_total_agro: '最大潜在伤害',
    record_max_damage_scouting: '最大侦查伤害',
    // Weapon record
    weapon_max_frags: '最多击杀',
    weapon_total_frags: '总击杀',
    weapon_hit_ratio: '命中率',
    /// App name section
    app_name: 'WoWs Info 起源+',
    wowsinfo_black: '黑',
    wowsinfo_white: '白',
    wowsinfo_ultra: '超级版',
    wowsinfo_ultimate: '究极版',
    wowsinfo_pro: '专业版',
    wowsinfo_new: '新',
    wowsinfo_go: 'GO',
    wowsinfo_origin: '起源',
    wowsinfo_free: '自由版',
    /// RS section
    // Tips
    rs_tip_download: '1. 下载',
    rs_tip_one: 'Please visit this Github repository and download the latest release. This program does not use lots of RAM and storage. Currently, it is in its beta stage and has no GUI.\n',
    rs_tip_setup: '2. 设置',
    rs_tip_two: "Copy and paste the path of your game folder into this program and you have to run it with admin or it will not work. It won't do anything harmful to your computer.\n",
    rs_tip_enjoy: '3. 使用RS',
    rs_tip_three: 'Enter the IP address you see on the screen and WoWs Info will start giving you real-time statistics for both teams.\n',
    /// Error section
    // General errors
    error_title: '错误',
    error_download_issue: '无法更新数据，\n请稍后重试。\n\n如果问题依然存在，请尝试修改DNS或者使用VPN。\n如果还是不可以的话，说明服务器正在维护中。',
    /// About WoWs Info section
    // Github link
    abour_github_link: 'https://github.com/HenryQuan/WoWs-Info-Origin/blob/master/README.md',
    unlock_pro_features: '解锁全部功能',
  },
  'zh-hant': {
    /// Setup section
    setup_title: '設置WoWs Info',
    setup_done_button: '完成',
    setup_loading: '加載中...',
    /// Home section
    // Friend section
    friend_clan_title: '工會',
    friend_player_title: '玩家',
    // Update section
    update_version_title: '版本信息',
    update_app_version: 'APP版本 ->',
    update_game_version: '遊戲版本 ->',
    // Button section
    button_settings_label: '設置',
    button_menu_label: '主菜單',
    button_back_label: '返回',
    button_home_label: '主頁面',
    /// Wiki section
    wiki_warship_footer: '篩選',
    wiki_warship_filter_btn: '確定',
    wiki_warship_reset_btn: '還原',
    wiki_warship_filter_placeholder: '輸入船名',
    wiki_warship_filter_tier: '等級',
    wiki_warship_filter_nation: '國家/區域',
    wiki_warship_filter_type: '類型',
    wiki_warship_filter_premium: '金幣船',
    // Warship Detail
    warship_unkown: '未知',
    warship_model: '3D模型',
    warship_update_module: '更新組件',
    warship_default_module: '默認組件',
    warship_apply_module: '確定',
    warship_survivability: '生存力',
    warship_survivability_health: '血量',
    warship_survivability_armour: '裝甲',
    warship_survivability_protection: '防護',
    warship_artillery: '火炮',
    warship_artillery_main: '主炮',
    warship_avg_damage: '平均傷害',
    warship_avg_winrate: '平均勝率',
    warship_avg_frag: '平均擊殺',
    warship_weapon_reload: '裝填時間',
    warship_weapon_range: '射程',
    warship_weapon_configuration: '配置',
    warship_weapon_dispersion: '最大散步',
    warship_weapon_rotation: '轉動時間',
    warship_weapon_fire_chance: '點火率',
    warship_artillery_main_weight: '重量',
    warship_weapon_damage: '最大傷害',
    warship_weapon_potential_damage: '潛在傷害',
    warship_weapon_ap_overmatch: '碾壓',
    warship_weapon_he_penetration: '穿深',
    warship_weapon_speed: '速度',
    warship_ramming: '沖撞',
    warship_artillery_secondary: '副炮',
    warship_torpedoes: '魚雷',
    warship_torpedoes_visible_distance: '探測距離',
    warship_antiaircraft: '防空',
    warship_maneuverabilty: '機動性',
    warship_maneuverabilty_turning: '轉舵半徑',
    warship_maneuverabilty_speed: '最大航速',
    warship_maneuverabilty_rudder_time: '轉舵時間',
    warship_aircraft: '飛機',
    warship_concealment: '隱蔽',
    warship_concealment_detect_by_ship: '被船發現距離',
    warship_concealment_detect_by_plane: '被飛機發現距離',
    warship_upgrades: '升級品',
    warship_next_ship: '可升級為',
    warship_compare_similar: '對比類似的戰艦',
    /// Menu section
    /// Settings section
    server_name: ['俄服', '歐服', '美服', '亞服'],
    setting_game_server: '遊戲服務器',
    setting_api_language: 'API語言',
    setting_app_language: 'WoWs Info語言',
    settings_api_settings: 'API接口設置',
    settings_app_settings: '軟件設置',
    settings_app_dark_mode: '夜間模式',
    settings_app_theme_colour: '主題顏色',
    settings_app_no_image_mode: '無圖模式',
    settings_app_swap_buttons: '交換下面的按鈕',
    settings_app_send_feedback: '反饋',
    settings_app_send_feedback_subtitle: '給開發者發郵件',
    settings_app_report_issues: '報告錯誤',
    settings_app_write_review: '給軟件打分',
    settings_app_share: '分享',
    settings_app_share_subtitle: '如果喜歡使用WoWs Info，記得分享給小夥伴們！',
    settings_app_check_for_update: '檢查更新',
    settings_app_no_update: '已經是最新版本',
    settings_app_has_update: '下載 {0} 版本',
    settings_open_source: '開源相關',
    settings_open_source_github: 'Github',
    settings_open_source_licence: '三方許可',
    settings_open_source_licence_subtitle: 'WoWs Info使用了很多優秀的三方組件',
    // Footer
    menu_footer: '開始搜索',
    menu_search_player: '玩家',
    menu_search_clan: '工會',
    // Search bar
    search_player_online: '在線',
    // Wiki
    wiki_section_title: '戰艦百科',
    wiki_achievement: '成就',
    wiki_warships: '戰艦',
    wiki_upgrades: '升級品',
    wiki_flags: '旗子與迷彩',
    wiki_skills: '艦長技能',
    wiki_skills_tier: '等級',
    wiki_skills_reset: '還原',
    wiki_skills_point: '點',
    wiki_maps: '地圖',
    wiki_collections: '收藏',
    // Extra
    extra_section_title: '其他',
    extra_support_wowsinfo: '支持WoWs Info',
    extra_rs_beta: '實時數據 Beta',
    extra_rs_beta_download: '在電腦上下載RS',
    extra_support_wowsinfo_subtitle: '捐助以及廣告',
    support_paypal: 'PayPal',
    support_patreon: 'Patreon',
    support_wechat: '微信',
    support_ads: '廣告設置',
    support_ads_banner: '顯示廣告',
    support_ads_fullscreen: '啟動APP時顯示廣告',
    // Websites
    website_title: '網站',
    website_official_site: '戰艦世界官網',
    website_premium: '戰艦商城',
    website_global_wiki: '戰艦全球百科',
    website_dev_blog: '開發者的臉書',
    website_sea_group: 'SEA Group',
    website_daily_bounce: 'The Daily Bounce',
    website_numbers: '戰艦數字',
    website_today: '今日戰艦',
    website_ranking: '玩家排行榜',
    website_models: '戰艦模型',
    // YouTubers
    youtuber_title: '油管主',
    youtuber_official: '戰艦世界官方頻道',
    youtuber_flambass: '艦長 Flambass',
    youtuber_notser: '艦長 Notser',
    youtuber_jingles: '艦長 The Mighty Jingles',
    youtuber_panzerknacker: '艦長 Panzerknacker',
    youtuber_flamu: '艦長 Flamu',
    youtuber_yuro: '艦長 Yuro',
    youtuber_iChaseGaming: '艦長 iChaseGaming',
    youtuber_NoZoupForYou: '艦長 NoZoupForYou',
    // Tools
    tool_title: '工具',
    /// Player section
    // Tabs
    tab_achievement_title: '成就',
    tab_graph_title: '圖表',
    tab_ship_title: '戰艦',
    tab_rank_title: '排位賽',
    // Rating
    rating_title: '個人評分',
    rating_description: '用來測量玩家的技能',
    rating_read_more: '- 閱讀更多 -',
    rating_warning: '請不要只用數據來評價玩家',
    rating_author: '艦長 Wiochi',
    rating_scale: '評分表',
    rating_bad: '還需努力',
    rating_below_average: '低於平均',
    rating_average: '平均水平',
    rating_good: '好',
    rating_very_good: '很好',
    rating_great: '非常好',
    rating_unicum: '大佬平均',
    rating_super_unicum: '神佬平均',
    rating_Unkwown: '水平未知',
    // Basic
    basic_data_unknown: '未知',
    basic_level_tier: '等級',
    basic_register_date: '註冊日期',
    basic_last_battle: '最後的戰鬥',
    basic_more_stat: '- 顯示更多數據 -',
    basic_add_friend: '增加到列表',
    basic_set_main: '設為主賬號',
    // Detailed
    detailed_win: '勝利',
    detailed_draw: '平局',
    detailed_loss: '失敗',
    detailed_survived: '存活場數',
    detailed_total_xp: '總經驗',
    detailed_survived_win: '存活勝利',
    detailed_survival_rate: '生存率',
    detailed_survivied_win_rate: '存活勝率',
    detailed_total_potential_damage: '總潛在傷害',
    detailed_avg_potential_damage: '平均潛在傷害',
    detailed_total_torp_potential_damage: '魚雷潛在傷害',
    detailed_avg_torp_potential_damage: '平均魚雷潛在傷害',
    detailed_total_scouting_damage: '總偵查傷害',
    detailed_avg_scouting_damage: '平均偵查傷害',
    detailed_total_damage: '總傷害',
    detailed_damage_potential_ratio: '真實傷害 / 潛在傷害',
    detailed_total_spotted: '總偵測數',
    detailed_avg_spotted: '平均偵測',
    detailed_total_frag: '總擊殺',
    detailed_frag_spot_ratio: '擊殺 / 偵測',
    detailed_total_plane_killed: '總飛機擊落',
    detailed_avg_plane_killed: '平均飛機擊落',
    // Ship detail
    ship_detail_damage: '傷害',
    ship_detail_winrate: '勝率',
    ship_detail_frag: '擊殺',
    ship_sort_battle: '场数',
    ship_sort_colour: '颜色',
    // Rank
    rank_season_title: '賽季',
    // Clan
    clan_created_date: '創建於',
    clan_creator_name: '創建者',
    clan_leader_name: '指揮官',
    clan_member_title: '成員',
    // Record
    record_title: '記錄',
    record_best_ship: '最好',
    record_max_damage_dealt: '最大傷害',
    record_max_frags_battle: '最多擊殺',
    record_max_planes_killed: '最多飛機擊落',
    record_max_xp: '最多經驗',
    record_max_ships_spotted: '最多偵測',
    record_max_total_agro: '最大潛在傷害',
    record_max_damage_scouting: '最大偵查傷害',
    // Weapon record
    weapon_max_frags: '最多擊殺',
    weapon_total_frags: '總擊殺',
    weapon_hit_ratio: '命中率',
    /// App name section
    app_name: 'WoWs Info 起源+',
    wowsinfo_black: '黑',
    wowsinfo_white: '白',
    wowsinfo_ultra: '超級版',
    wowsinfo_ultimate: '究極版',
    wowsinfo_pro: '專業版',
    wowsinfo_new: '新',
    wowsinfo_go: 'GO',
    wowsinfo_origin: '起源',
    wowsinfo_free: '自由版',
    /// RS section
    // Tips
    rs_tip_download: '1. 下載',
    rs_tip_one: 'Please visit this Github repository and download the latest release. This program does not use lots of RAM and storage. Currently, it is in its beta stage and has no GUI.\n',
    rs_tip_setup: '2. 設置',
    rs_tip_two: "Copy and paste the path of your game folder into this program and you have to run it with admin or it will not work. It won't do anything harmful to your computer.\n",
    rs_tip_enjoy: '3. 使用RS',
    rs_tip_three: 'Enter the IP address you see on the screen and WoWs Info will start giving you real-time statistics for both teams.\n',
    /// Error section
    // General errors
    error_title: '錯誤',
    error_download_issue: '無法更新數據，\n請稍後重試。\n\n如果問題依然存在，請嘗試修改DNS或者使用VPN。\n如果還是不可以的話，說明服務器正在維護中。',
    /// About WoWs Info section
    // Github link
    abour_github_link: 'https://github.com/HenryQuan/WoWs-Info-Origin/blob/master/README.md',
    unlock_pro_features: '解鎖全部功能',
  },
  ja: {
    /// Setup section
    setup_title: 'WoWs Infoの初期設定',
    setup_done_button: '完了',
    setup_loading: 'Loading...',
    /// Home section
    // Friend section
    friend_clan_title: 'クラン',
    friend_player_title: 'プレーヤー',
    // Update section
    update_version_title: 'バージョン',
    update_app_version: 'アプリ ->',
    update_game_version: 'ゲーム ->',
    // Button section
    button_settings_label: '設定',
    button_menu_label: 'メニュー',
    button_back_label: '戻る',
    button_home_label: 'ホーム',
    /// Wiki section
    wiki_warship_footer: 'フィルター',
    wiki_warship_filter_btn: 'はい',
    wiki_warship_reset_btn: 'リセット',
    wiki_warship_filter_placeholder: '名前を入力する',
    wiki_warship_filter_tier: 'ティア',
    wiki_warship_filter_nation: '国家／地区',
    wiki_warship_filter_type: '艦種',
    wiki_warship_filter_premium: 'プレミアム艦艇',
    // Warship Detail
    warship_unkown: '不明',
    warship_model: '3Dモデル',
    warship_update_module: 'モジュールを変える',
    warship_default_module: '初期モジュール',
    warship_apply_module: 'はい',
    warship_survivability: '抗堪性',
    warship_survivability_health: 'HP',
    warship_survivability_armour: '装甲',
    warship_survivability_protection: '対水雷防御',
    warship_artillery: '砲',
    warship_artillery_main: '主砲',
    warship_avg_damage: '平均与ダメージ',
    warship_avg_winrate: '勝率',
    warship_avg_frag: '艦船撃沈',
    warship_weapon_reload: '装填時間',
    warship_weapon_range: '射程',
    warship_weapon_configuration: '配置',
    warship_weapon_dispersion: '最大散布界',
    warship_weapon_rotation: '旋回時間',
    warship_weapon_fire_chance: '火災発生率',
    warship_artillery_main_weight: '重量',
    warship_weapon_damage: '最大与ダメージ',
    warship_weapon_potential_damage: '潜在ダメージ',
    warship_weapon_ap_overmatch: 'オーバーマッチ',
    warship_weapon_he_penetration: '装甲貫通力',
    warship_weapon_speed: '速度',
    warship_ramming: '体当たり',
    warship_artillery_secondary: '副砲',
    warship_torpedoes: '魚雷',
    warship_torpedoes_visible_distance: '発見距離',
    warship_antiaircraft: '対空火力',
    warship_maneuverabilty: '機動性',
    warship_maneuverabilty_turning: '旋回半径',
    warship_maneuverabilty_speed: '最大速度',
    warship_maneuverabilty_rudder_time: '転舵時間',
    warship_aircraft: '航空機',
    warship_concealment: '隠蔽性',
    warship_concealment_detect_by_ship: '海面発見距離',
    warship_concealment_detect_by_plane: '航空発見距離',
    warship_upgrades: 'アップグレード',
    warship_next_ship: '次の艦艇',
    warship_compare_similar: '似ている艦艇のチャート',
    /// Menu section
    /// Settings section
    server_name: ['ロシア', 'ヨーロッパ', '北アメリカ', 'アジア'],
    setting_game_server: 'ゲームサーバ',
    setting_api_language: 'APIの言語',
    setting_app_language: 'WoWs Infoの言語',
    settings_api_settings: 'APIの設定',
    settings_app_settings: 'アプリの設定',
    settings_app_dark_mode: 'ナイトモード',
    settings_app_theme_colour: 'テーマ色',
    settings_app_no_image_mode: '省データモード',
    settings_app_swap_buttons: '底部ボタンスワップ',
    settings_app_send_feedback: 'フィードバック',
    settings_app_send_feedback_subtitle: '開発者にメール',
    settings_app_report_issues: 'バグの報告',
    settings_app_write_review: 'レビューを書く',
    settings_app_share: 'シェア',
    settings_app_share_subtitle: '良かったらシェアしてね＞＿＜',
    settings_app_check_for_update: 'アップデートをチェック',
    settings_app_no_update: '最新バージョンです',
    settings_app_has_update: 'アップデート有り {0}',
    settings_open_source: 'オープンソース',
    settings_open_source_github: 'Github',
    settings_open_source_licence: 'ライセンス',
    settings_open_source_licence_subtitle: '本アプリは以下のモジュールを使って頂いました。',
    // Footer
    menu_footer: 'サーチ',
    menu_search_player: 'プレーヤー',
    menu_search_clan: 'クラン',
    // Search bar
    search_player_online: 'オンライン',
    // Wiki
    wiki_section_title: '百科事典',
    wiki_achievement: '実績',
    wiki_warships: '艦艇',
    wiki_upgrades: 'アップグレード',
    wiki_flags: '信号旗',
    wiki_skills: '艦長スキル',
    wiki_skills_tier: 'ティア',
    wiki_skills_reset: 'リセット',
    wiki_skills_point: 'ポイント',
    wiki_maps: '地図',
    wiki_collections: 'コレクション',
    // Extra
    extra_section_title: 'その他',
    extra_support_wowsinfo: 'WoWs Infoへの支援',
    extra_rs_beta: 'リアルタイム統計 Beta',
    extra_rs_beta_download: 'パソコンでダウンロード',
    extra_support_wowsinfo_subtitle: 'ドネーションと広告',
    support_paypal: 'ペイパル　PayPal',
    support_patreon: 'パトレオン　Patreon',
    support_wechat: '微信　WeChat',
    support_ads: '広告の設定',
    support_ads_banner: '広告を見せる',
    support_ads_fullscreen: 'アプリを開く時に広告を見せる',
    // Websites
    website_title: 'ウェブサイト',
    website_official_site: 'World of Warships',
    website_premium: 'プレミアムショップ',
    website_global_wiki: 'グローバルウィキ',
    website_dev_blog: '開発者のフェイスブック',
    website_sea_group: 'シーグループ',
    website_daily_bounce: 'ザデーリーバウンス',
    website_numbers: 'WoWS Stats & Numbers',
    website_today: 'Warships.Today',
    website_ranking: 'プレーヤーランキング',
    website_models: '艦艇モデル',
    // YouTubers
    youtuber_title: 'ユーチューバー',
    youtuber_official: 'WoWsの公式チャンネル',
    youtuber_flambass: 'Flambass',
    youtuber_notser: 'Notser',
    youtuber_jingles: 'The Mighty Jingles',
    youtuber_panzerknacker: 'Panzerknacker',
    youtuber_flamu: 'Flamu',
    youtuber_yuro: 'Yuro',
    youtuber_iChaseGaming: 'iChaseGaming',
    youtuber_NoZoupForYou: 'NoZoupForYou',
    // Tools
    tool_title: 'ツール',
    /// Player section
    // Tabs
    tab_achievement_title: '実績',
    tab_graph_title: 'チャート',
    tab_ship_title: '艦艇',
    tab_rank_title: 'ランク',
    // Rating
    rating_title: '操艦技術',
    rating_description: 'レベルの評判方法である',
    rating_read_more: '- 詳しい情報 -',
    rating_warning: 'レートによって、人を評価するのはやめなさい',
    rating_author: 'By Wiochi',
    rating_scale: '色スケール',
    rating_bad: 'きっと未來がある',
    rating_below_average: '普通以下',
    rating_average: '普通',
    rating_good: '良い',
    rating_very_good: 'とても良い',
    rating_great: 'グレート',
    rating_unicum: 'ユニカム',
    rating_super_unicum: 'スーパーユニカム',
    rating_Unkwown: '不明',
    // Basic
    basic_data_unknown: '不明',
    basic_level_tier: 'レベル',
    basic_register_date: '登録した日',
    basic_last_battle: '最後の戦い',
    basic_more_stat: '- もっと見る -',
    basic_add_friend: 'フレンドに追加',
    basic_set_main: 'メインプレヤーにセット',
    // Detailed
    detailed_win: '勝利',
    detailed_draw: '引き分け',
    detailed_loss: '敗北',
    detailed_survived: '生還',
    detailed_total_xp: '総経験値',
    detailed_survived_win: '生還勝利',
    detailed_survival_rate: '生還率',
    detailed_survivied_win_rate: '生還勝率',
    detailed_total_potential_damage: '総潜在ダメージ',
    detailed_avg_potential_damage: '平均潜在ダメージ',
    detailed_total_torp_potential_damage: '総水雷潜在ダメージ',
    detailed_avg_torp_potential_damage: '平均水雷潜在ダメージ',
    detailed_total_scouting_damage: '総発見によるダメージ',
    detailed_avg_scouting_damage: '平均発見によるダメージ',
    detailed_total_damage: '総与ダメージ',
    detailed_damage_potential_ratio: '与ダメージ / 潜在',
    detailed_total_spotted: '総艦艇発見数',
    detailed_avg_spotted: '平均艦艇発見数',
    detailed_total_frag: '総艦艇撃沈数',
    detailed_frag_spot_ratio: '艦艇撃沈 / 艦艇発見',
    detailed_total_plane_killed: '総航空機撃墜数',
    detailed_avg_plane_killed: '平均航空機撃墜数',
    // Ship detail
    ship_detail_damage: '与ダメージ',
    ship_detail_winrate: '勝率',
    ship_detail_frag: '艦船撃沈',
    ship_sort_battle: '戦闘数',
    ship_sort_colour: '色',
    // Rank
    rank_season_title: 'シーズン',
    // Clan
    clan_created_date: '始まりの日',
    clan_creator_name: 'クリエーター',
    clan_leader_name: 'クランマスター',
    clan_member_title: 'メンバー',
    // Record
    record_title: '記録',
    record_best_ship: '一番のは',
    record_max_damage_dealt: '最大与ダメージ',
    record_max_frags_battle: '最大艦艇撃沈数',
    record_max_planes_killed: '最大航空機撃墜数',
    record_max_xp: '最大経験値',
    record_max_ships_spotted: '最大艦艇発見数',
    record_max_total_agro: '最大潜在ダメージ',
    record_max_damage_scouting: '最大発見によるダメージ',
    // Weapon record
    weapon_max_frags: '最大艦艇撃沈数',
    weapon_total_frags: '総艦艇撃沈数',
    weapon_hit_ratio: '命中率',
    /// App name section
    app_name: 'WoWs Info オリジン+',
    wowsinfo_black: '黒',
    wowsinfo_white: '白',
    wowsinfo_ultra: 'ウルトラ',
    wowsinfo_ultimate: 'アルティメット',
    wowsinfo_pro: 'プロ',
    wowsinfo_new: 'ニュー',
    wowsinfo_go: 'ゴー',
    wowsinfo_origin: 'オリジン',
    wowsinfo_free: '自由',
    /// RS section
    // Tips
    rs_tip_download: '1. ダウンロード',
    rs_tip_one: 'Please visit this Github repository and download the latest release. This program does not use lots of RAM and storage. Currently, it is in its beta stage and has no GUI.\n',
    rs_tip_setup: '2. Setup',
    rs_tip_two: "Copy and paste the path of your game folder into this program and you have to run it with admin or it will not work. It won't do anything harmful to your computer.\n",
    rs_tip_enjoy: '3. Enjoy',
    rs_tip_three: 'Enter the IP address you see on the screen and WoWs Info will start giving you real-time statistics for both teams.\n',
    /// Error section
    // General errors
    error_title: 'エラー',
    error_download_issue: 'アップデート失敗\nやり直してください\n\nいつも失敗の場合はVPNを使ったりDNSを変えたりしてみてください\nメンテナンスを行う可能性もある',
    /// About WoWs Info section
    // Github link
    abour_github_link: 'https://github.com/HenryQuan/WoWs-Info-Origin/blob/master/README.md',
    unlock_pro_features: '全ての機能を解除する',
  },
  id: {
    /// Setup section
    setup_title: 'Pengaturan WoWs Info',
    setup_done_button: 'Selesai',
    setup_loading: 'Memproses...',
    /// Home section
    // Friend section
    friend_clan_title: 'Clan',
    friend_player_title: 'Player',
    // Update section
    update_version_title: 'Versi',
    update_app_version: 'Aplikasi ->',
    update_game_version: 'Game ->',
    // Button section
    button_settings_label: 'Pengaturan',
    button_menu_label: 'Menu',
    button_back_label: 'Kembali',
    button_home_label: 'Beranda',
    /// Wiki section
    wiki_warship_footer: 'Filter',
    wiki_warship_filter_btn: 'Apply',
    wiki_warship_reset_btn: 'Reset',
    wiki_warship_filter_placeholder: 'Masukan nama kapal',
    wiki_warship_filter_tier: 'Tier',
    wiki_warship_filter_nation: 'Kebangsaan',
    wiki_warship_filter_type: 'Tipe',
    wiki_warship_filter_premium: 'Kapal premium',
    // Warship Detail
    warship_unkown: 'Unknown',
    warship_model: 'Model 3D',
    warship_update_module: 'Perbarui modul kapal',
    warship_default_module: 'Default',
    warship_apply_module: 'Apply',
    warship_survivability: 'Survivability',
    warship_survivability_health: 'Health',
    warship_survivability_armour: 'Armour',
    warship_survivability_protection: 'Protection',
    warship_artillery: 'Artillery',
    warship_artillery_main: 'Main Battery',
    warship_avg_damage: 'Average Damage',
    warship_avg_winrate: 'Average Winrate',
    warship_avg_frag: 'Average Frags',
    warship_weapon_reload: 'Reload Time',
    warship_weapon_range: 'Range',
    warship_weapon_configuration: 'Configuration',
    warship_weapon_dispersion: 'Max Dispersion',
    warship_weapon_rotation: 'Rotation Time',
    warship_weapon_fire_chance: 'Fire Chance',
    warship_artillery_main_weight: 'Weight',
    warship_weapon_damage: 'Max Damage',
    warship_weapon_potential_damage: 'Potential Damage',
    warship_weapon_ap_overmatch: 'Overmatch',
    warship_weapon_he_penetration: 'Penetration',
    warship_weapon_speed: 'Speed',
    warship_ramming: 'Ramming',
    warship_artillery_secondary: 'Secondary',
    warship_torpedoes: 'Torpedoes',
    warship_torpedoes_visible_distance: 'Detection',
    warship_antiaircraft: 'AA Defense',
    warship_maneuverabilty: 'Maneuverabilty',
    warship_maneuverabilty_turning: 'Turning Radius',
    warship_maneuverabilty_speed: 'Max Speed',
    warship_maneuverabilty_rudder_time: 'Rudder Time',
    warship_aircraft: 'Aircraft',
    warship_concealment: 'Concealment',
    warship_concealment_detect_by_ship: 'Detection by Ship',
    warship_concealment_detect_by_plane: 'Detection by Plane',
    warship_upgrades: 'Upgrades',
    warship_next_ship: 'Next ship(s)',
    warship_compare_similar: 'Compare similar ships',
    /// Menu section
    /// Settings section
    server_name: ['Russia', 'Europe', 'North America', 'Asia'],
    setting_game_server: 'Game Server',
    setting_api_language: 'Pengaturan bahasa API',
    setting_app_language: 'Pengaturan bahasa Aplikasi',
    settings_api_settings: 'Pengaturan API',
    settings_app_settings: 'Pengaturan Aplikasi',
    settings_app_dark_mode: 'Dark mode',
    settings_app_theme_colour: 'Warna tema',
    settings_app_no_image_mode: 'Mode aplikasi tanpa gambar',
    settings_app_swap_buttons: 'Tukar tombol bagian bawah',
    settings_app_send_feedback: 'Feedback',
    settings_app_send_feedback_subtitle: 'Kirim email ke developer',
    settings_app_report_issues: 'Laporkan isu',
    settings_app_write_review: 'Tulis ulasan',
    settings_app_share: 'Share aplikasi ke teman',
    settings_app_share_subtitle: 'Share WoWs Info jika anda menyukai app ini!',
    settings_app_check_for_update: 'Periksa pembaruan',
    settings_app_no_update: 'Anda sudah menggunakan aplikasi dengan versi terbaru.',
    settings_app_has_update: 'Ada {0} pembaruan baru',
    settings_open_source: 'Open Source',
    settings_open_source_github: 'Github',
    settings_open_source_licence: 'Licences',
    settings_open_source_licence_subtitle: 'Modul yang dipakai oleh WoWs Info',
    // Footer
    menu_footer: 'Pencarian',
    menu_search_player: 'Player',
    menu_search_clan: 'Clan',
    // Search bar
    search_player_online: 'online',
    // Wiki
    wiki_section_title: 'Encyclopedia',
    wiki_achievement: 'Achievement',
    wiki_warships: 'Warships',
    wiki_upgrades: 'Upgrades',
    wiki_flags: 'Flags/Camouflages',
    wiki_skills: 'Commander Skills',
    wiki_skills_tier: 'Tier',
    wiki_skills_reset: 'Reset',
    wiki_skills_point: 'point(s)',
    wiki_maps: 'Maps',
    wiki_collections: 'Collections',
    // Extra
    extra_section_title: 'Extra',
    extra_support_wowsinfo: 'Support WoWs Info',
    extra_rs_beta: 'Realtime Statistics Beta',
    extra_rs_beta_download: 'Download RS on your computer',
    extra_support_wowsinfo_subtitle: 'Donations and Ads',
    support_paypal: 'PayPal',
    support_patreon: 'Patreon',
    support_wechat: 'WeChat',
    support_ads: 'Ads Settings',
    support_ads_banner: 'Show Ads',
    support_ads_fullscreen: 'Show Ads on launch',
    // Websites
    website_title: 'Websites',
    website_official_site: 'World of Warships',
    website_premium: 'Premium Shop',
    website_global_wiki: 'Global Wiki',
    website_dev_blog: 'Developer Blog',
    website_sea_group: 'SEA Group',
    website_daily_bounce: 'The Daily Bounce',
    website_numbers: 'WoWS Stats & Numbers',
    website_today: 'Warships.Today',
    website_ranking: 'Player Ranking',
    website_models: 'Warships Models',
    // YouTubers
    youtuber_title: 'YouTubers',
    youtuber_official: 'WoWs Official',
    youtuber_flambass: 'Flambass',
    youtuber_notser: 'Notser',
    youtuber_jingles: 'The Mighty Jingles',
    youtuber_panzerknacker: 'Panzerknacker',
    youtuber_flamu: 'Flamu',
    youtuber_yuro: 'Yuro',
    youtuber_iChaseGaming: 'iChaseGaming',
    youtuber_NoZoupForYou: 'NoZoupForYou',
    // Tools
    tool_title: 'Tools',
    /// Player section
    // Tabs
    tab_achievement_title: 'Achievement',
    tab_graph_title: 'Graph',
    tab_ship_title: 'Ship',
    tab_rank_title: 'Rank',
    // Rating
    rating_title: 'Personal Rating',
    rating_description: 'It is a measure of skill.',
    rating_read_more: '- Read More -',
    rating_warning: 'Please do not judge other players simply by his/her rating',
    rating_author: 'By Wiochi',
    rating_scale: 'Colour Scale',
    rating_bad: 'Improvement Needed',
    rating_below_average: 'Below Average',
    rating_average: 'Average',
    rating_good: 'Good',
    rating_very_good: 'Very Good',
    rating_great: 'Great',
    rating_unicum: 'Unicum',
    rating_super_unicum: 'SUPER Unicum',
    rating_Unkwown: 'Unknown',
    // Basic
    basic_data_unknown: 'Unknown',
    basic_level_tier: 'Level',
    basic_register_date: 'Register Date',
    basic_last_battle: 'Last Battle',
    basic_more_stat: '- Show More -',
    basic_add_friend: 'Tambahkan ke lis',
    basic_set_main: 'Set Sebagai Akun Utama',
    // Detailed
    detailed_win: 'Wins',
    detailed_draw: 'Draws',
    detailed_loss: 'Losses',
    detailed_survived: 'Survived Battles',
    detailed_total_xp: 'Total XP',
    detailed_survived_win: 'Survived Wins',
    detailed_survival_rate: 'Survival Rate',
    detailed_survivied_win_rate: 'Survived Win Rate',
    detailed_total_potential_damage: 'Total Potential Damage',
    detailed_avg_potential_damage: 'Avg Potential Damage',
    detailed_total_torp_potential_damage: 'Total Torp Potential Damage',
    detailed_avg_torp_potential_damage: 'Avg Torp Potential Damage',
    detailed_total_scouting_damage: 'Total Scouting Damage',
    detailed_avg_scouting_damage: 'Avg Scouting Damage',
    detailed_total_damage: 'Total Damage Dealt',
    detailed_damage_potential_ratio: 'Damage Dealt / Potential',
    detailed_total_spotted: 'Total Spotted',
    detailed_avg_spotted: 'Avg Spotted',
    detailed_total_frag: 'Total Frags',
    detailed_frag_spot_ratio: 'Frag / Spotted',
    detailed_total_plane_killed: 'Total Planed Destroyed',
    detailed_avg_plane_killed: 'Avg Planed Destroyed',
    // Ship detail
    ship_detail_damage: 'Damage',
    ship_detail_winrate: 'Winrate',
    ship_detail_frag: 'Frags',
    ship_sort_battle: 'Battle',
    ship_sort_colour: 'Colour',
    // Rank
    rank_season_title: 'Season',
    // Clan
    clan_created_date: 'Tanggal Pembuatan',
    clan_creator_name: 'Pembuat',
    clan_leader_name: 'Pemimpin',
    clan_member_title: 'Anggota',
    // Record
    record_title: 'Records',
    record_best_ship: 'Best Ship',
    record_max_damage_dealt: 'Max Damage Dealt',
    record_max_frags_battle: 'Max Frags',
    record_max_planes_killed: 'Max Planes Destroyed',
    record_max_xp: 'Max XP',
    record_max_ships_spotted: 'Max Ships Spotted',
    record_max_total_agro: 'Max Potential Damage Dealt',
    record_max_damage_scouting: 'Max Scouting Damage',
    // Weapon record
    weapon_max_frags: 'Max Frags',
    weapon_total_frags: 'Total Frags',
    weapon_hit_ratio: 'Hit Ratio',
    /// App name section
    app_name: 'WoWs Info Origin+',
    wowsinfo_black: 'Black',
    wowsinfo_white: 'White',
    wowsinfo_ultra: 'Ultra',
    wowsinfo_ultimate: 'Ultimate',
    wowsinfo_pro: 'Pro',
    wowsinfo_new: 'New',
    wowsinfo_go: 'Go',
    wowsinfo_origin: 'Origin',
    wowsinfo_free: 'Free',
    /// RS section
    // Tips
    rs_tip_download: '1. Download',
    rs_tip_one: 'Please visit this Github repository and download the latest release. This program does not use lots of RAM and storage. Currently, it is in its beta stage and has no GUI.\n',
    rs_tip_setup: '2. Setup',
    rs_tip_two: "Copy and paste the path of your game folder into this program and you have to run it with admin or it will not work. It won't do anything harmful to your computer.\n",
    rs_tip_enjoy: '3. Enjoy',
    rs_tip_three: 'Enter the IP address you see on the screen and WoWs Info will start giving you real-time statistics for both teams.\n',
    /// Error section
    // General errors
    error_title: 'Error',
    error_download_issue: 'Gagal untuk mengupdate data. \nSilakan coba kembali.',
    /// About WoWs Info section
    // Github link
    abour_github_link: 'https://github.com/HenryQuan/WoWs-Info-Origin/blob/master/README.md',
    unlock_pro_features: 'Unlock Pro features',
  }
});