import LocalizedStrings from 'react-native-localization';

export const lang = new LocalizedStrings({
  en: {
    /// Setup section
    setup_title: 'Setup WoWs Info',
    setup_done_button: 'Done',
    setup_loading: 'Loading...',
    /// Home section
    // Friend section
    friend_clan_title: 'Clan',
    friend_player_title: 'Player',
    // Update section
    update_version_title: 'Version',
    update_app_version: 'App ->',
    update_game_version: 'Game ->',
    // Button section
    button_settings_label: 'Settings',
    button_menu_label: 'Menu',
    button_back_label: 'Go Back',
    button_home_label: 'Home',
    /// Wiki section
    wiki_warship_footer: 'Filter',
    wiki_warship_filter_btn: 'Apply',
    wiki_warship_reset_btn: 'Reset',
    wiki_warship_filter_placeholder: 'Enter a ship name',
    wiki_warship_filter_tier: 'Tier',
    wiki_warship_filter_nation: 'Nation',
    wiki_warship_filter_type: 'Type',
    wiki_warship_filter_premium: 'Premium ship',
    // Warship Detail
    warship_unkown: 'Unknown',
    warship_model: '3D Model',
    warship_update_module: 'Update ship modules',
    warship_default_module: 'Default',
    warship_apply_module: 'Apply',
    warship_survivability: 'Survivablity',
    warship_survivability_health: 'Health',
    warship_survivability_armour: 'Armour',
    warship_survivability_protection: 'Protection',
    warship_artillery: 'Artillery',
    warship_artillery_main: 'Main Battery',
    warship_avg_damage: 'Average Damage',
    warship_avg_winrate: 'Average Winrate',
    warship_avg_frag: 'Average Frags',
    warship_weapon_reload: 'Reload Time',
    warship_weapon_range: 'Range',
    warship_weapon_configuration: 'Configuration',
    warship_weapon_dispersion: 'Max Dispersion',
    warship_weapon_rotation: 'Rotation Time',
    warship_weapon_fire_chance: 'Fire Chance',
    warship_artillery_main_weight: 'Weight',
    warship_weapon_damage: 'Max Damage',
    warship_weapon_potential_damage: 'Potential Damage',
    warship_weapon_ap_overmatch: 'Overmatch',
    warship_weapon_he_penetration: 'Penetration',
    warship_weapon_speed: 'Speed',
    warship_ramming: 'Ramming',
    warship_artillery_secondary: 'Secondary',
    warship_torpedoes: 'Torpedoes',
    warship_torpedoes_visible_distance: 'Detection',
    warship_antiaircraft: 'AA Defense',
    warship_maneuverabilty: 'Maneuverabilty',
    warship_maneuverabilty_turning: 'Turning Radius',
    warship_maneuverabilty_speed: 'Max Speed',
    warship_maneuverabilty_rudder_time: 'Rudder Time',
    warship_aircraft: 'Aircraft',
    warship_concealment: 'Concealment',
    warship_concealment_detect_by_ship: 'Detection by Ship',
    warship_concealment_detect_by_plane: 'Detection by Plane',
    warship_upgrades: 'Upgrades',
    warship_next_ship: 'Next ship(s)',
    /// Menu section
    /// Settings section
    server_name: ['Russia', 'Europe', 'North Ameria', 'Asia'],
    settings_api_settings: 'API Settings',
    settings_app_settings: 'App Settings',
    settings_app_dark_mode: 'Dark mode',
    settings_app_theme_colour: 'Theme colour',
    settings_app_swap_buttons: 'Swap bottom buttons',
    settings_app_send_feedback: 'Feedback',
    settings_app_send_feedback_subtitle: 'Send an email to developer',
    settings_app_report_issues: 'Report an issue',
    settings_app_write_review: 'Write a review',
    settings_app_share: 'Share with friends',
    settings_app_share_subtitle: 'Share WoWs Info if you enjoy using it!',
    settings_open_source: 'Open Source',
    settings_open_source_github: 'Github',
    settings_open_source_licence: 'Licences',
    settings_open_source_licence_subtitle: 'Great modules that are used by WoWs Info',
    // Footer
    menu_footer: 'Search',
    menu_search_player: 'Player',
    menu_search_clan: 'Clan',
    // Search bar
    search_player_online: 'online',
    // Wiki
    wiki_section_title: 'Encyclopedia',
    wiki_achievement: 'Achievement',
    wiki_warships: 'Warships',
    wiki_upgrades: 'Upgrades',
    wiki_flags: 'Flags/Camouflages',
    wiki_skills: 'Commander Skills',
    wiki_skills_tier: 'Tier',
    wiki_skills_reset: 'Reset',
    wiki_skills_point: 'point(s)',
    wiki_maps: 'Maps',
    wiki_collections: 'Collections',
    // Extra
    extra_section_title: 'Extra',
    extra_support_wowsinfo: 'Support WoWs Info',
    // Websites
    website_title: 'Websites',
    website_official_site: 'World of Warships',
    website_premium: 'Premium Shop',
    website_global_wiki: 'Global Wiki',
    website_dev_blog: 'Developer Blog',
    website_sea_group: 'SEA Group',
    website_daily_bounce: 'The Daily Bounce',
    website_numbers: 'WoWS Stats & Numbers',
    website_today: 'Warships.Today',
    website_ranking: 'Player Ranking',
    website_models: 'Warships Models',
    // YouTubers
    youtuber_title: 'YouTubers',
    youtuber_official: 'WoWs Official',
    youtuber_flambass: 'Flambass',
    youtuber_notser: 'Notser',
    youtuber_jingles: 'The Mighty Jingles',
    youtuber_panzerknacker: 'Panzerknacker',
    youtuber_flamu: 'Flamu',
    youtuber_yuro: 'Yuro',
    youtuber_iChaseGaming: 'iChaseGaming',
    youtuber_NoZoupForYou: 'NoZoupForYou',
    // Tools
    tool_title: 'Tools',
    /// Player section
    // Tabs
    tab_achievement_title: 'Achievement',
    tab_graph_title: 'Graph',
    tab_ship_title: 'Ship',
    tab_rank_title: 'Rank',
    // Rating
    rating_title: 'Personal Rating',
    rating_description: 'It is a measure of skill.',
    rating_read_more: '- Read More -',
    rating_warning: 'Please do not judge other players simply by his/her rating',
    rating_author: 'By Wiochi',
    rating_scale: 'Colour Scale',
    rating_bad: 'Improvement Needed',
    rating_below_average: 'Below Average',
    rating_average: 'Average',
    rating_good: 'Good',
    rating_very_good: 'Very Good',
    rating_great: 'Great',
    rating_unicum: 'Unicum',
    rating_super_unicum: 'SUPER Unicum',
    rating_Unkwown: 'Unknown',
    // Basic
    basic_data_unknown: 'Unknown',
    basic_level_tier: 'Level',
    basic_register_date: 'Register Date',
    basic_last_battle: 'Last Battle',
    basic_more_stat: '- Show More -',
    // Detailed
    detailed_win: 'Wins',
    detailed_draw: 'Draws',
    detailed_loss: 'Losses',
    detailed_survived: 'Survived Battles',
    detailed_total_xp: 'Total XP',
    detailed_survived_win: 'Survived Wins',
    detailed_survival_rate: 'Survival Rate',
    detailed_survivied_win_rate: 'Survived Win Rate',
    detailed_total_potential_damage: 'Total Potential Damage',
    detailed_avg_potential_damage: 'Avg Potential Damage',
    detailed_total_torp_potential_damage: 'Total Torp Potential Damage',
    detailed_avg_torp_potential_damage: 'Avg Torp Potential Damage',
    detailed_total_scouting_damage: 'Total Scouting Damage',
    detailed_avg_scouting_damage: 'Avg Scouting Damage',
    detailed_total_damage: 'Total Damage Dealt',
    detailed_damage_potential_ratio: 'Damage Dealt / Potential',
    detailed_total_spotted: 'Total Spotted',
    detailed_avg_spotted: 'Avg Spotted',
    detailed_total_frag: 'Total Frags',
    detailed_frag_spot_ratio: 'Frag / Spotted',
    detailed_total_plane_killed: 'Total Planed Destroyed',
    detailed_avg_plane_killed: 'Avg Planed Destroyed',
    // Ship detail
    ship_detail_damage: 'Damage',
    ship_detail_winrate: 'Winrate',
    ship_detail_frag: 'Frags',
    // Rank
    rank_season_title: 'Season',
    // Clan
    clan_created_date: 'Created At',
    clan_creator_name: 'Creator',
    clan_leader_name: 'Leader',
    clan_member_title: 'Member',
    // Record
    record_title: 'Records',
    record_best_ship: 'Best Ship',
    record_max_damage_dealt: 'Max Damage Dealt',
    record_max_frags_battle: 'Max Frags',
    record_max_planes_killed: 'Max Planes Destroyed',
    record_max_xp: 'Max XP',
    record_max_ships_spotted: 'Max Ships Spotted',
    record_max_total_agro: 'Max Potential Damage Dealt',
    record_max_damage_scouting: 'Max Scouting Damage',
    // Weapon record
    weapon_max_frags: 'Max Frags',
    weapon_total_frags: 'Total Frags',
    weapon_hit_ratio: 'Hit Ratio',
    /// App name section
    app_name: 'WoWs Info Origin',
    wowsinfo_black: 'Black',
    wowsinfo_white: 'White',
    wowsinfo_ultra: 'Ultra',
    wowsinfo_ultimate: 'Ultimate',
    wowsinfo_pro: 'Pro',
    wowsinfo_new: 'New',
    wowsinfo_go: 'Go',
    wowsinfo_origin: 'Origin',
    wowsinfo_free: 'Free',
    /// RS section
    // Tips
    rs_tip_download: '1. Download',
    rs_tip_one: 'Please visit this Github repository and download the latest release. This program does not use lots of RAM and storage. Currently, it is in its beta stage and has no GUI.\n',
    rs_tip_setup: '2. Setup',
    rs_tip_two: "Copy and paste the path of your game folder into this program and you have to run it with admin or it will not work. It won't do anything harmful to your computer.\n",
    rs_tip_enjoy: '3. Enjoy',
    rs_tip_three: 'Enter the IP address you see on the screen and WoWs Info will start giving you real-time statistics for both teams.\n',
    /// Error section
    // General erros
    error_title: 'Error',
    error_download_issue: 'Failed to update data. \nPlease try again later.'
  },
  zh: {
    /// Setup section
    setup_title: '设置WoWs Info',
    setup_done_button: '完成',
    setup_loading: '加载中...',
    /// Home section
    // Friend section
    friend_clan_title: '工会',
    friend_player_title: '玩家',
    // Update section
    update_version_title: '版本信息',
    update_app_version: 'APP版本 ->',
    update_game_version: '游戏版本 ->',
    // Button section
    button_settings_label: '设置',
    button_menu_label: '主菜单',
    button_back_label: '返回',
    button_home_label: '主页面',
    /// Wiki section
    wiki_warship_footer: '筛选',
    wiki_warship_filter_btn: '确定',
    wiki_warship_reset_btn: '还原',
    wiki_warship_filter_placeholder: '输入船名',
    wiki_warship_filter_tier: '等级',
    wiki_warship_filter_nation: '国家/区域',
    wiki_warship_filter_type: '类型',
    wiki_warship_filter_premium: '金币船',
    // Warship Detail
    warship_unkown: '未知',
    warship_model: '3D模型',
    warship_update_module: '更新组件',
    warship_default_module: '默认组件',
    warship_apply_module: '确定',
    warship_survivability: '生存力',
    warship_survivability_health: '血量',
    warship_survivability_armour: '装甲',
    warship_survivability_protection: '防护',
    warship_artillery: '火炮',
    warship_artillery_main: '主炮',
    warship_avg_damage: '平均伤害',
    warship_avg_winrate: '平均胜率',
    warship_avg_frag: '平均击杀',
    warship_weapon_reload: '装填时间',
    warship_weapon_range: '射程',
    warship_weapon_configuration: '配置',
    warship_weapon_dispersion: '最大散步',
    warship_weapon_rotation: '转动时间',
    warship_weapon_fire_chance: '点火率',
    warship_artillery_main_weight: '重量',
    warship_weapon_damage: '最大伤害',
    warship_weapon_potential_damage: '潜在伤害',
    warship_weapon_ap_overmatch: '碾压',
    warship_weapon_he_penetration: '穿深',
    warship_weapon_speed: '速度',
    warship_ramming: '冲撞',
    warship_artillery_secondary: '副炮',
    warship_torpedoes: '鱼雷',
    warship_torpedoes_visible_distance: '探测距离',
    warship_antiaircraft: '放空',
    warship_maneuverabilty: '机动性',
    warship_maneuverabilty_turning: '转舵半径',
    warship_maneuverabilty_speed: '最大航速',
    warship_maneuverabilty_rudder_time: '转舵时间',
    warship_aircraft: '飞机',
    warship_concealment: '隐蔽',
    warship_concealment_detect_by_ship: '被船发现距离',
    warship_concealment_detect_by_plane: '被飞机发现距离',
    warship_upgrades: '升级品',
    warship_next_ship: '可升级为',
    /// Menu section
    /// Settings section
    server_name: ['俄服', '欧服', '美服', '亚服'],
    settings_api_settings: 'API接口设置',
    settings_app_settings: '软件设置',
    settings_app_dark_mode: '夜间模式',
    settings_app_theme_colour: '主题颜色',
    settings_app_swap_buttons: '交换下面的按钮',
    settings_app_send_feedback: '反馈',
    settings_app_send_feedback_subtitle: '给开发者发一封邮件',
    settings_app_report_issues: '报告错误',
    settings_app_write_review: '给软件打分',
    settings_app_share: '分享',
    settings_app_share_subtitle: '如果喜欢使用WoWs Info，记得分享给小伙伴们！',
    settings_open_source: '开源相关',
    settings_open_source_github: 'Github',
    settings_open_source_licence: '三方许可',
    settings_open_source_licence_subtitle: 'WoWs Info使用了很多优秀的三方组件',
    // Footer
    menu_footer: '开始搜索',
    menu_search_player: '玩家',
    menu_search_clan: '工会',
    // Search bar
    search_player_online: '在线',
    // Wiki
    wiki_section_title: '战舰百科',
    wiki_achievement: '成就',
    wiki_warships: '战舰',
    wiki_upgrades: '升级品',
    wiki_flags: '旗子与迷彩',
    wiki_skills: '舰长技能',
    wiki_skills_tier: '等级',
    wiki_skills_reset: '还原',
    wiki_skills_point: '点',
    wiki_maps: '地图',
    wiki_collections: '收藏',
    // Extra
    extra_section_title: '其他',
    extra_support_wowsinfo: '支持WoWs Info',
    // Websites
    website_title: '网站',
    website_official_site: '战舰世界官网',
    website_premium: '战舰商城',
    website_global_wiki: '战舰全球百科',
    website_dev_blog: '开发者的脸书',
    website_sea_group: 'SEA Group',
    website_daily_bounce: 'The Daily Bounce',
    website_numbers: '战舰数字',
    website_today: '今日战舰',
    website_ranking: '玩家排行榜',
    website_models: '战舰模型',
    // YouTubers
    youtuber_title: '油管主',
    youtuber_official: '战舰世界官方频道',
    youtuber_flambass: '舰长 Flambass',
    youtuber_notser: '舰长 Notser',
    youtuber_jingles: '舰长 The Mighty Jingles',
    youtuber_panzerknacker: '舰长 Panzerknacker',
    youtuber_flamu: '舰长 Flamu',
    youtuber_yuro: '舰长 Yuro',
    youtuber_iChaseGaming: '舰长 iChaseGaming',
    youtuber_NoZoupForYou: '舰长 NoZoupForYou',
    // Tools
    tool_title: '工具',
    /// Player section
    // Tabs
    tab_achievement_title: '成就',
    tab_graph_title: '图表',
    tab_ship_title: '战舰',
    tab_rank_title: '排位赛',
    // Rating
    rating_title: '个人评分 - Personal Rating',
    rating_description: '用来测量玩家的技能',
    rating_read_more: '- 阅读更多 -',
    rating_warning: '请不要只用数据来评价玩家',
    rating_author: '舰长 Wiochi',
    rating_scale: '评分表',
    rating_bad: '还需努力',
    rating_below_average: '低于平均',
    rating_average: '平均水平',
    rating_good: '好',
    rating_very_good: '很好',
    rating_great: '非常好',
    rating_unicum: '大佬平均',
    rating_super_unicum: '神佬平均',
    rating_Unkwown: '水平未知',
    // Basic
    basic_data_unknown: '未知',
    basic_level_tier: '等级',
    basic_register_date: '注册日期',
    basic_last_battle: '最后的战斗',
    basic_more_stat: '- 显示更多数据 -',
    // Detailed
    detailed_win: '胜利',
    detailed_draw: '平局',
    detailed_loss: '失败',
    detailed_survived: '存活场数',
    detailed_total_xp: '总经验',
    detailed_survived_win: '存活胜利',
    detailed_survival_rate: '生存率',
    detailed_survivied_win_rate: '存活胜率',
    detailed_total_potential_damage: '总潜在伤害',
    detailed_avg_potential_damage: '平均潜在伤害',
    detailed_total_torp_potential_damage: '鱼雷潜在伤害',
    detailed_avg_torp_potential_damage: '平均鱼雷潜在伤害',
    detailed_total_scouting_damage: '总侦查伤害',
    detailed_avg_scouting_damage: '平均侦查伤害',
    detailed_total_damage: '总伤害',
    detailed_damage_potential_ratio: '真实伤害 / 潜在伤害',
    detailed_total_spotted: '总侦测数',
    detailed_avg_spotted: '平均侦测',
    detailed_total_frag: '总击杀',
    detailed_frag_spot_ratio: '击杀 / 侦测',
    detailed_total_plane_killed: '总飞机击落',
    detailed_avg_plane_killed: '平均飞机击落',
    // Ship detail
    ship_detail_damage: '伤害',
    ship_detail_winrate: '胜率',
    ship_detail_frag: '击杀',
    // Rank
    rank_season_title: '赛季',
    // Clan
    clan_created_date: '创建于',
    clan_creator_name: '创建者',
    clan_leader_name: '指挥官',
    clan_member_title: '成员',
    // Record
    record_title: '记录',
    record_best_ship: '最好',
    record_max_damage_dealt: '最大伤害',
    record_max_frags_battle: '最多击杀',
    record_max_planes_killed: '最多飞机击落',
    record_max_xp: '最多经验',
    record_max_ships_spotted: '最多侦测',
    record_max_total_agro: '最大潜在伤害',
    record_max_damage_scouting: '最大侦查伤害',
    // Weapon record
    weapon_max_frags: '最多击杀',
    weapon_total_frags: '总击杀',
    weapon_hit_ratio: '命中率',
    /// App name section
    app_name: 'WoWs Info 起源',
    wowsinfo_black: '黑',
    wowsinfo_white: '白',
    wowsinfo_ultra: '超级版',
    wowsinfo_ultimate: '究极版',
    wowsinfo_pro: '专业版',
    wowsinfo_new: '新',
    wowsinfo_go: 'GO',
    wowsinfo_origin: '起源',
    wowsinfo_free: '自由版',
    /// RS section
    // Tips
    rs_tip_download: '1. 下载',
    rs_tip_one: 'Please visit this Github repository and download the latest release. This program does not use lots of RAM and storage. Currently, it is in its beta stage and has no GUI.\n',
    rs_tip_setup: '2. 设置',
    rs_tip_two: "Copy and paste the path of your game folder into this program and you have to run it with admin or it will not work. It won't do anything harmful to your computer.\n",
    rs_tip_enjoy: '3. 使用RS',
    rs_tip_three: 'Enter the IP address you see on the screen and WoWs Info will start giving you real-time statistics for both teams.\n',
    /// Error section
    // General erros
    error_title: '错误',
    error_download_issue: '无法更新数据。\n请稍后重试。'
  },
  'zh-hant': {
    /// Setup section
    setup_title: '設置WoWs Info',
    setup_done_button: '完成',
    setup_loading: '加載中...',
    /// Home section
    // Friend section
    friend_clan_title: '工會',
    friend_player_title: '玩家',
    // Update section
    update_version_title: '版本信息',
    update_app_version: 'APP版本 ->',
    update_game_version: '遊戲版本 ->',
    // Button section
    button_settings_label: '設置',
    button_menu_label: '主菜單',
    button_back_label: '返回',
    button_home_label: '主頁面',
    /// Wiki section
    wiki_warship_footer: '篩選',
    wiki_warship_filter_btn: '確定',
    wiki_warship_reset_btn: '還原',
    wiki_warship_filter_placeholder: '輸入船名',
    wiki_warship_filter_tier: '等級',
    wiki_warship_filter_nation: '國家/區域',
    wiki_warship_filter_type: '類型',
    wiki_warship_filter_premium: '金幣船',
    // Warship Detail
    warship_unkown: '未知',
    warship_model: '3D模型',
    warship_update_module: '更新組件',
    warship_default_module: '默認組件',
    warship_apply_module: '確定',
    warship_survivability: '生存力',
    warship_survivability_health: '血量',
    warship_survivability_armour: '裝甲',
    warship_survivability_protection: '防護',
    warship_artillery: '火炮',
    warship_artillery_main: '主炮',
    warship_avg_damage: '平均傷害',
    warship_avg_winrate: '平均勝率',
    warship_avg_frag: '平均擊殺',
    warship_weapon_reload: '裝填時間',
    warship_weapon_range: '射程',
    warship_weapon_configuration: '配置',
    warship_weapon_dispersion: '最大散步',
    warship_weapon_rotation: '轉動時間',
    warship_weapon_fire_chance: '點火率',
    warship_artillery_main_weight: '重量',
    warship_weapon_damage: '最大傷害',
    warship_weapon_potential_damage: '潛在傷害',
    warship_weapon_ap_overmatch: '碾壓',
    warship_weapon_he_penetration: '穿深',
    warship_weapon_speed: '速度',
    warship_ramming: '沖撞',
    warship_artillery_secondary: '副炮',
    warship_torpedoes: '魚雷',
    warship_torpedoes_visible_distance: '探測距離',
    warship_antiaircraft: '放空',
    warship_maneuverabilty: '機動性',
    warship_maneuverabilty_turning: '轉舵半徑',
    warship_maneuverabilty_speed: '最大航速',
    warship_maneuverabilty_rudder_time: '轉舵時間',
    warship_aircraft: '飛機',
    warship_concealment: '隱蔽',
    warship_concealment_detect_by_ship: '被船發現距離',
    warship_concealment_detect_by_plane: '被飛機發現距離',
    warship_upgrades: '升級品',
    warship_next_ship: '可升級為',
    /// Menu section
    /// Settings section
    server_name: ['俄服', '歐服', '美服', '亞服'],
    settings_api_settings: 'API接口設置',
    settings_app_settings: '軟件設置',
    settings_app_dark_mode: '夜間模式',
    settings_app_theme_colour: '主題顏色',
    settings_app_swap_buttons: '交換下面的按鈕',
    settings_app_send_feedback: '反饋',
    settings_app_send_feedback_subtitle: '給開發者發壹封郵件',
    settings_app_report_issues: '報告錯誤',
    settings_app_write_review: '給軟件打分',
    settings_app_share: '分享',
    settings_app_share_subtitle: '如果喜歡使用WoWs Info，記得分享給小夥伴們！',
    settings_open_source: '開源相關',
    settings_open_source_github: 'Github',
    settings_open_source_licence: '三方許可',
    settings_open_source_licence_subtitle: 'WoWs Info使用了很多優秀的三方組件',
    // Footer
    menu_footer: '開始搜索',
    menu_search_player: '玩家',
    menu_search_clan: '工會',
    // Search bar
    search_player_online: '在線',
    // Wiki
    wiki_section_title: '戰艦百科',
    wiki_achievement: '成就',
    wiki_warships: '戰艦',
    wiki_upgrades: '升級品',
    wiki_flags: '旗子與迷彩',
    wiki_skills: '艦長技能',
    wiki_skills_tier: '等級',
    wiki_skills_reset: '還原',
    wiki_skills_point: '點',
    wiki_maps: '地圖',
    wiki_collections: '收藏',
    // Extra
    extra_section_title: '其他',
    extra_support_wowsinfo: '支持WoWs Info',
    // Websites
    website_title: '網站',
    website_official_site: '戰艦世界官網',
    website_premium: '戰艦商城',
    website_global_wiki: '戰艦全球百科',
    website_dev_blog: '開發者的臉書',
    website_sea_group: 'SEA Group',
    website_daily_bounce: 'The Daily Bounce',
    website_numbers: '戰艦數字',
    website_today: '今日戰艦',
    website_ranking: '玩家排行榜',
    website_models: '戰艦模型',
    // YouTubers
    youtuber_title: '油管主',
    youtuber_official: '戰艦世界官方頻道',
    youtuber_flambass: '艦長 Flambass',
    youtuber_notser: '艦長 Notser',
    youtuber_jingles: '艦長 The Mighty Jingles',
    youtuber_panzerknacker: '艦長 Panzerknacker',
    youtuber_flamu: '艦長 Flamu',
    youtuber_yuro: '艦長 Yuro',
    youtuber_iChaseGaming: '艦長 iChaseGaming',
    youtuber_NoZoupForYou: '艦長 NoZoupForYou',
    // Tools
    tool_title: '工具',
    /// Player section
    // Tabs
    tab_achievement_title: '成就',
    tab_graph_title: '圖表',
    tab_ship_title: '戰艦',
    tab_rank_title: '排位賽',
    // Rating
    rating_title: '個人評分 - Personal Rating',
    rating_description: '用來測量玩家的技能',
    rating_read_more: '- 閱讀更多 -',
    rating_warning: '請不要只用數據來評價玩家',
    rating_author: '艦長 Wiochi',
    rating_scale: '評分表',
    rating_bad: '還需努力',
    rating_below_average: '低於平均',
    rating_average: '平均水平',
    rating_good: '好',
    rating_very_good: '很好',
    rating_great: '非常好',
    rating_unicum: '大佬平均',
    rating_super_unicum: '神佬平均',
    rating_Unkwown: '水平未知',
    // Basic
    basic_data_unknown: '未知',
    basic_level_tier: '等級',
    basic_register_date: '註冊日期',
    basic_last_battle: '最後的戰鬥',
    basic_more_stat: '- 顯示更多數據 -',
    // Detailed
    detailed_win: '勝利',
    detailed_draw: '平局',
    detailed_loss: '失敗',
    detailed_survived: '存活場數',
    detailed_total_xp: '總經驗',
    detailed_survived_win: '存活勝利',
    detailed_survival_rate: '生存率',
    detailed_survivied_win_rate: '存活勝率',
    detailed_total_potential_damage: '總潛在傷害',
    detailed_avg_potential_damage: '平均潛在傷害',
    detailed_total_torp_potential_damage: '魚雷潛在傷害',
    detailed_avg_torp_potential_damage: '平均魚雷潛在傷害',
    detailed_total_scouting_damage: '總偵查傷害',
    detailed_avg_scouting_damage: '平均偵查傷害',
    detailed_total_damage: '總傷害',
    detailed_damage_potential_ratio: '真實傷害 / 潛在傷害',
    detailed_total_spotted: '總偵測數',
    detailed_avg_spotted: '平均偵測',
    detailed_total_frag: '總擊殺',
    detailed_frag_spot_ratio: '擊殺 / 偵測',
    detailed_total_plane_killed: '總飛機擊落',
    detailed_avg_plane_killed: '平均飛機擊落',
    // Ship detail
    ship_detail_damage: '傷害',
    ship_detail_winrate: '勝率',
    ship_detail_frag: '擊殺',
    // Rank
    rank_season_title: '賽季',
    // Clan
    clan_created_date: '創建於',
    clan_creator_name: '創建者',
    clan_leader_name: '指揮官',
    clan_member_title: '成員',
    // Record
    record_title: '記錄',
    record_best_ship: '最好',
    record_max_damage_dealt: '最大傷害',
    record_max_frags_battle: '最多擊殺',
    record_max_planes_killed: '最多飛機擊落',
    record_max_xp: '最多經驗',
    record_max_ships_spotted: '最多偵測',
    record_max_total_agro: '最大潛在傷害',
    record_max_damage_scouting: '最大偵查傷害',
    // Weapon record
    weapon_max_frags: '最多擊殺',
    weapon_total_frags: '總擊殺',
    weapon_hit_ratio: '命中率',
    /// App name section
    app_name: 'WoWs Info 起源',
    wowsinfo_black: '黑',
    wowsinfo_white: '白',
    wowsinfo_ultra: '超級版',
    wowsinfo_ultimate: '究極版',
    wowsinfo_pro: '專業版',
    wowsinfo_new: '新',
    wowsinfo_go: 'GO',
    wowsinfo_origin: '起源',
    wowsinfo_free: '自由版',
    /// RS section
    // Tips
    rs_tip_download: '1. 下載',
    rs_tip_one: 'Please visit this Github repository and download the latest release. This program does not use lots of RAM and storage. Currently, it is in its beta stage and has no GUI.\n',
    rs_tip_setup: '2. 設置',
    rs_tip_two: "Copy and paste the path of your game folder into this program and you have to run it with admin or it will not work. It won't do anything harmful to your computer.\n",
    rs_tip_enjoy: '3. 使用RS',
    rs_tip_three: 'Enter the IP address you see on the screen and WoWs Info will start giving you real-time statistics for both teams.\n',
    /// Error section
    // General erros
    error_title: '錯誤',
    error_download_issue: '無法更新數據。\n請稍後重試。'
  },
  ja: {

  },
  id: {

  }
});