# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WoWsInfo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WoWsInfo
  pod 'FBAudienceNetwork', '~> 5.1.0'

end
