# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WoWsInfo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WoWsInfo

  pod 'ReactNativeExceptionHandler', :path => '../node_modules/react-native-exception-handler'

  pod 'RNIap', :path => '../node_modules/react-native-iap'

  pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'


  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


  pod 'ReactNativeLocalization', :path => '../node_modules/react-native-localization'

end
